### ISSUE TITLE
Can't make SayText work

### ISSUE THREAD

**Issue by ardimaunahan** [KishCom/anki-vector-nodejs#1]
Here's my code:
```
vector.client.SayText(
  {
    text: "Hello World",
    use_vector_voice: true,
    duration_scalar: 1
  },
  (err, result) => {
    if (err) {
      console.log("Error", err);
    } else console.log(result);
  }
);
```

I'm getting this error:
```
Error { Error: 13 INTERNAL: Failed to say text
...
  code: 13,
  metadata: Metadata { _internal_repr: {} },
  details: 'Failed to say text' }
```

Hope you can help providing an actual working code for this use case. I'm using the latest Vector OS (1.4.1.2806)

Thanks!

**Comment by aRkker** [comment]
I am having the same issue, but I think it is because of the change they did to the robot requiring behavior control for things like the SayText and a few other ones. I am unable to get control via the BehaviorControl call though, it just hangs indefinitely

**Comment by aRkker** [comment]
Okay, after playing around with it a little and looking into python and the C# version of the API, I found that this works:

```js
        let behaviorStream = vector.client.BehaviorControl();

        behaviorStream.write({control_request: {priority: 20}}, null,  (err, res) => {
           
            vector.client.DriveOffCharger({}, (err, res) => {
                vector.client.SayText({text: 'Hello world', use_vector_voice: false, duration_scalar: 1.0}, (err, res) => {
                    if (err) 
                        console.error(err);

                    console.log(res);
                 })      
            });       
        })
```

That control request needs to be sent for a lot of other functions to work as well, keep that in mind.

**Comment by ardimaunahan** [comment]
> Okay, after playing around with it a little and looking into python and the C# version of the API, I found that this works:
> 
> ```js
>         let behaviorStream = vector.client.BehaviorControl();
> 
>         behaviorStream.write({control_request: {priority: 20}}, null,  (err, res) => {
>            
>             vector.client.DriveOffCharger({}, (err, res) => {
>                 vector.client.SayText({text: 'Hello world', use_vector_voice: false, duration_scalar: 1.0}, (err, res) => {
>                     if (err) 
>                         console.error(err);
> 
>                     console.log(res);
>                  })      
>             });       
>         })
> ```
> 
> That control request needs to be sent for a lot of other functions to work as well, keep that in mind.

Thanks @aRkker, code is working!
