### ISSUE TITLE
protoLoader.loadSync not finding proto file

### ISSUE THREAD

**Issue by bgordley** [KishCom/anki-vector-nodejs#2]
Hi there, it appears that when executing the code from the readme the protoLoader module is not able to locate the `./protobufs/anki_vector/messaging/external_interface.proto` file.

Here is the error message I receive:
`Error: ENOENT: no such file or directory, open 'protobufs/anki_vector/messaging/external_interface.proto'`

I forked the repo to see if I am able to come up with a solution.

**Comment by JoshMolyneux** [comment]
Was there any conclusion on this?

**Comment by KishCom** [comment]
What version of Node and what OS?

**Comment by JoshMolyneux** [comment]
For myself:
Node: v12.14.0
OS: Win 10 Pro

**Comment by KishCom** [comment]
OK! I'll give that a test out tonight. I developed it using Node v10 on Linux and OSX.
